### ISSUE TITLE
Create a Signup Page

### ISSUE THREAD

**Issue by Pradeep241094** [KirubelTolosa/Covid-19_MDPatientFollowUP#2]
The signup Page constitute

User Name
Email ID
Password Field
and a Submit button to sign up into the app.

**Comment by KirubelTolosa** [comment]
There won't be a use-case where we expect a user to signup. Instead, the medical provider will create a user(or enlist a patient in other words) once they test positive. Thus the medical provider creates a patient by inserting a userID and password which will be handed to the patient in person. I'd say we don't sweat this for the moment because it has to do with medical laws and the provider's database. 

(the idea being ...let's hold this signup page for the moment).

**Comment by Pradeep241094** [comment]
Completed
